### ISSUE TITLE
Feature Request: Fedora IoT-based images

### ISSUE THREAD

**Issue by keplersj** [ublue-os/ucore#111]
I've just installed Fedora IoT to a home server NUC I have, and would like to leverage the additions made to the ucore-hci image on this machine. I tried to rebase to the ucore-hci image on the IoT installation, but could not get the deployment to boot. I imagine an image based on the IoT image with these additions would allow for an easy immutable server installation.

**Comment by bsherman** [comment]
@keplersj appreciate the feature request, though I doubt we'll be making "iot" images as part of the ucore stream. The reason is that Fedor IoT follows the regular Fedora release model (eg, 38, 39, 40), whereas Fedora CoreOS is a rolling release (stable, testing, next).  The differences are subtle, especially since both streams use the same Fedora package repos.

Even if the release model were compatible, I'm not aware of an container-native-ostree image for Fedora IoT. Both the ucore and ublue desktop images are only happening since those images are available from Fedora upstream.


That said, @noelmiller has some experience switching between ucore(CoreOS) and bazzite(desktop), and we were recently discussing if he'd be able to document some of the tricks he discovered to make it possible to switch back and forth.

**Comment by noelmiller** [comment]
Hi @keplersj !

Sorry it took me so long to get back to you on this. I think we got to the bottom of why rebasing from Fedora IOT to CoreOS doesn't work very well. If you use the default partition layout that IOT installs with, it is using LVM. LVM does not work with ucore or upstream CoreOS. If you install Fedora IOT with a standard EXT4 partition layout, the rebase will work successfully. 

I didn't do any further testing, so I'm not sure if there are any other gotchas that I'm not seeing immediately. I would recommend using the default install method that we provide for ucore.

@bsherman may have more insights here, but that is what we have discovered. 

Thanks, 

Noel Miller

**Comment by bsherman** [comment]
The request to use Fedora IoT just moved a step towards possible...

https://discussion.fedoraproject.org/t/f40-change-proposal-fedora-iot-bootable-containers/101958

If this change lands in F40, Fedora IoT would at least be able to benefit from the uBlue style of build/customization tooling.

**Comment by bsherman** [comment]
And THIS https://discussion.fedoraproject.org/t/f40-change-proposal-iot-simplified-provisioning-self-contained/101964 would allow for Fedora IoT to be installed similar-to/just-like CoreOS with ignition and coreos-installer.
