### ISSUE TITLE
Create systemd auto-update service and timer to replicate Zicanti service as a workaround

### ISSUE THREAD

**Issue by Nitrousoxide** [ublue-os/ucore#64]
Currently, Zicanti does not work with a custom image for CoreOS.  As such updates become a manual ordeal.  IoT has had this issue as well and the generally accepted practice over there is to create a systemd service and timer to update ostree and reboot if it sees it's not booted to the most up-to-date deployment.

https://discussion.fedoraproject.org/t/how-to-actually-enable-automatic-updates-in-fedora-iot/77061/3

Describes how to implement it.

**Comment by cubt85iz** [comment]
I believe there are three plausible use cases here and I think some clarification on the expectations for this issue would be  needed before assistance could be provided.

Here are the three use cases I thought of:
1. User wishes to automatically upgrade and reboot using custom date/time window.
2. User wishes to automatically upgrade and doesn't care when the reboot would occur.
3. User wishes to automatically upgrade and doesn't want to reboot.

I'm still familiarizing myself with the project, but since static images are being generated is allowing for user choice an issue?

**Comment by LeoSum8** [comment]
I am currently reading up on this project as I am looking for a way to run coreos with my zfs pools from my old truenas setup.

One big point for me would be auto updates. 

How do users of ucore handle updating currently? Is it a manual task as of now?
